sudo: false
language: python
matrix:
  include:
    # all supported Python versions
    - python: 2.7
      env:
        - USECURL=7.60.0-openssl11-gssapi-libssh2
        - USESSL=openssl
        - USEOPENSSL=1.1.0h
        - TESTDOCSEXAMPLES=1
    - python: 2.7
      env:
        - USECURL=7.60.0-openssl10-gssapi-libssh2
        - USESSL=openssl
        - USEOPENSSL=1.0.2o
        - TESTDOCSEXAMPLES=1
    - python: 2.7
      env:
        - USECURL=7.60.0-gssapi-libssh2
        - USESSL=libressl
        - USELIBRESSL=2.2.0
    - python: 2.7
      env:
        - USECURL=7.60.0-gssapi-libssh2
        - USESSL=gnutls
        - TESTDOCSEXAMPLES=1
    - python: 2.7
      env:
        - USECURL=7.60.0-gssapi-libssh2
        - USESSL=nss
        # Examples fail with NSS due to CA certs not being explicitly given
        #- TESTDOCSEXAMPLES=1
    - python: 2.7
      env:
        # this configuration should be without gssapi
        - USECURL=7.60.0
        - USESSL=none
    - python: 3.2
      env:
        - USECURL=7.60.0-openssl10-gssapi-libssh2
        - USESSL=openssl
        - USEOPENSSL=1.0.2o
        - TESTDOCSEXAMPLES=1
    - python: 3.3
      env:
        - USECURL=7.60.0-openssl11-gssapi-libssh2
        - USESSL=openssl
        - USEOPENSSL=1.1.0h
        - TESTDOCSEXAMPLES=1
    - python: 3.4
      env:
        - USECURL=7.60.0-openssl10-gssapi-libssh2
        - USESSL=openssl
        - USEOPENSSL=1.0.2o
        - TESTDOCSEXAMPLES=1
    - python: 3.5
      env:
        - USECURL=7.60.0-openssl11-gssapi-libssh2
        - USESSL=openssl
        - USEOPENSSL=1.1.0h
        - TESTDOCSEXAMPLES=1
    - python: 3.6
      env:
        - USECURL=7.60.0-openssl11-gssapi-libssh2
        - USESSL=openssl
        - USEOPENSSL=1.1.0h
        - TESTDOCSEXAMPLES=1
    - python: 3.6
      env:
        - USECURL=7.60.0-gssapi-libssh2
        - USESSL=gnutls
        - TESTDOCSEXAMPLES=1
    - python: 3.6
      env:
        - USECURL=7.60.0-gssapi-libssh2
        - USESSL=nss
        # Examples fail with NSS due to CA certs not being explicitly given
        #- TESTDOCSEXAMPLES=1

    # minimum libcurl we support
    - python: 2.7
      env:
        - USECURL=7.19.0-gssapi
        - USESSL=openssl
        - TESTDOCSEXAMPLES=1

    # AVOIDSTDIO tested on one Python version, must be Python 2.x
    - python: 2.7
      env:
        - USECURL=7.60.0-gssapi-libssh2
        - USESSL=openssl
        - AVOIDSTDIO=yes
    
    # libcurl development head with various SSL backends
    - python: 2.7
      env:
        - USECURL=7.47.0-dev-gssapi-libssh2
        - USESSL=openssl
    - python: 2.7
      env:
        - USECURL=7.47.0-dev-gssapi-libssh2
        - USESSL=nss
    - python: 3.6
      env:
        - USECURL=7.47.0-dev-gssapi-libssh2
        - USESSL=openssl
    - python: 3.6
      env:
        - USECURL=7.47.0-dev-gssapi-libssh2
        - USESSL=nss

    # common distributions:
    # Debian Wheezy
    - python: 2.7
      env:
        - USECURL=7.26.0-gssapi
        - USESSL=gnutls
    # Debian Jessie
    - python: 3.4
      env:
        - USECURL=7.38.0-gssapi
        - USESSL=gnutls
install: >
  ./tests/travis/setup.sh
script: >
  ./tests/travis/run.sh
addons:
  apt:
    packages:
      - libssh2-1
