language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
matrix:
  include:
    - python: 2.7
      env: USEPY=3.1
    - python: 2.7
      env: USECURL=7.19.0
    - python: 2.7
      env:
        - USECURL=7.43.0
        - USESSL=openssl
    - python: 2.7
      env:
        - USECURL=7.43.0
        - USESSL=libressl
        - USELIBRESSL=2.2.0
    - python: 2.7
      env:
        - USECURL=7.43.0
        - USESSL=gnutls
    - python: 2.7
      env:
        - USECURL=7.43.0
        - USESSL=nss
    - python: 2.7
      env:
        - USECURL=7.43.0
        - USESSL=none
    - python: 2.7
      env:
        - USECURL=7.43.0-gssapi
        - USESSL=none
    - python: 2.7
      env:
        - AVOIDSTDIO=yes
install: >
  ./tests/travis/setup.sh
before_script: >
  ./tests/travis/hack.sh
script: >
  ./tests/travis/run.sh
