language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
matrix:
  include:
    - python: 2.7
      env: USEPY=3.1
    - python: 2.7
      env: USECURL=7.19.0
    - python: 2.7
      env:
        - USECURL=7.43.0
        - USESSL=openssl
    - python: 2.7
      env:
        - USECURL=7.43.0
        - USESSL=libressl
        - USELIBRESSL=2.2.0
    - python: 2.7
      env:
        - USECURL=7.43.0
        - USESSL=gnutls
    - python: 2.7
      env:
        - USECURL=7.43.0
        - USESSL=nss
    - python: 2.7
      env:
        - USECURL=7.43.0
        - USESSL=none
    - python: 2.7
      env:
        - USECURL=7.43.0-gssapi
        - USESSL=none
    - python: 2.7
      env:
        - AVOIDSTDIO=yes
    # centos 6
    - python: 2.6
      env:
        - USECURL=7.19.7-gssapi
        - USESSL=openssl
        - USEOPENSSL=1.0.1e
    # debian wheezy
    - python: 2.7
      env:
        - USECURL=7.26.0-gssapi
        - USESSL=gnutls
    # debian jessie
    - python: 3.4
      env:
        - USECURL=7.38.0-gssapi
        - USESSL=gnutls
install: >
  ./tests/travis/setup.sh
before_script: >
  ./tests/travis/hack.sh
script: >
  ./tests/travis/run.sh
