language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
install: >
  pip install -r requirements-dev.txt --use-mirrors &&
  sudo apt-get install vsftpd
script: >
  make &&
  export PYTHONPATH=build/lib.* &&
  export PYCURL_VSFTPD_PATH=/usr/sbin/vsftpd &&
  nosetests
