language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
install: >
  if test -e requirements-dev-$TRAVIS_PYTHON_VERSION.txt; then
    pip install -r requirements-dev-$TRAVIS_PYTHON_VERSION.txt --use-mirrors
  else
    pip install -r requirements-dev.txt --use-mirrors
  fi &&
  sudo apt-get install vsftpd
script: >
  make &&
  export PYTHONPATH=$(ls -d build/lib.*) &&
  export PYCURL_VSFTPD_PATH=/usr/sbin/vsftpd &&
  nosetests
